version: "3.9"

services:

  cache:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  database:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init/:/docker-entrypoint-initdb.d/

  server:
    container_name: spring
    image: ljh0728/life-cook-book-server:1.0
    ports:
      - 8080:8080
    depends_on:
      - cache
      - database

  client:
    container_name: nginx-react
    restart: always
    image: ljh0728/life-cook-book-client:1.0
    ports:
      - 3000:80

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local