version: "3.9"

services:

  cache:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - C:/Users/LJH/Coding/CS-yorisa-Project/redis/:/data

  database:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test1234
    volumes:
      - C:/Users/LJH/Coding/CS-yorisa-Project/pgdata/:/var/lib/postgresql/data

  application:
    container_name: spring
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/test_db
      SPRING_DATASOURCE_USERNAME: test_user
      SPRING_DATASOURCE_PASSWORD: test1234
    ports:
      - 8080:8080
    depends_on:
      - cache
      - database

  nginx:
    container_name: nginx-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
