version: "3.9"

services:

  cache:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  database:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}

  server:
    container_name: spring
    image: ljh0728/life-cook-book-server:latest
    ports:
      - 8080:8080
    depends_on:
      - cache
      - database

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local