version: "3.9"

services:

  cache:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
#      - C:/Users/LJH/Coding/study/CS-yorisa-Project/redis/:/data

  database:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test1234
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - C:/Users/LJH/Coding/study/CS-yorisa-Project/pgdata/:/var/lib/postgresql/data
      - ./postgres-init/:/docker-entrypoint-initdb.d/

  server:
    container_name: spring
    image: ljh0728/life-cook-book-server:1.0
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/test_db
      SPRING_DATASOURCE_USERNAME: test_user
      SPRING_DATASOURCE_PASSWORD: test1234
    depends_on:
      - cache
      - database

  client:
    container_name: nginx-react
    restart: always
    image: ljh0728/life-cook-book-client:1.0
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
    ports:
      - 3000:80
