type UserExpenseGoal{
    memberId: UUID,
    goalNo: Int,
    period: String,
    goalAmount: Long,
}

input UserExpenseGoalInput {
    memberId: UUID,
    period: String,
    goalAmount: Long,
}

input UserExpenseGoalUpdate {
    memberId: UUID,
    goalNo: Int,
    goalAmount: Long,
}

extend type Query{
    getUserExpenseGoal(memberId: UUID, period: String): UserExpenseGoal
    getUserExpense(memberId: UUID, period: String): BigDecimal
}

extend type Mutation {
    saveUserExpenseGoal(userGoal: UserExpenseGoalInput): UserExpenseGoal
    updateUserExpenseGoal(userGoal: UserExpenseGoalUpdate): UserExpenseGoal
}