spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  #  jwt:
  #    secret: ${JWT_TOKEN}
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update